version: "3"
services:
# My grafana service 
  grafana:
    build:
      context: .
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
